services:
  code-server:
    build: .
    container_name: code-server
    
    # This is the magic line. It runs the container as your
    # host user, which automatically fixes all permission errors.
    user: "${UID}:${GID}"
    environment:
      - TZ=America/Los_Angeles
      - PASSWORD=${CODE_SERVER_PASSWORD:-changeme}
    volumes:
      - vscode_ssh:/config/.ssh
      # Note: The paths are different for this image
      - vscode_config:/home/coder/.config
      - vscode_projects:/home/coder/project
    expose:
      - "8443"
    restart: unless-stopped

volumes:
  vscode_config:
  vscode_ssh:
  vscode_projects:
    external: true
    name: coder-server-cb8mmc_vscode_projects
