services:
  code-server:
    build: .
    container_name: code_server
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=America/Los_Angeles
      - PASSWORD=${CODE_SERVER_PASSWORD:-changeme}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - vscode_config:/config
      - vscode_projects:/config/workspace
      - vscode_ssh:/config/.ssh
    expose:
      - "8443"
    restart: unless-stopped

volumes:
  vscode_config:
  vscode_ssh:
  vscode_projects:
    external: true
    name: coder-server-cb8mmc_vscode_projects
