services:
  code-server:
    build: .
    container_name: code-server
    # Use root's UID and GID
    user: "0:0"
    environment:
      - TZ=America/Los_Angeles
      - PASSWORD=${CODE_SERVER_PASSWORD:-changeme}
    volumes:
      - vscode_ssh:/config/.ssh
      # Note: The paths are different for this image
      - vscode_config:/home/coder/.config
      - vscode_projects:/home/coder/project
    expose:
      - "8080"
    restart: unless-stopped

volumes:
  vscode_config:
  vscode_ssh:
  vscode_projects:
    external: true
    name: coder-server-cb8mmc_vscode_projects
